apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::486873673611:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-167IVP7HBNIQT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::486873673611:role/newUdacityFlaskDeployCBKubectlRole
      username: build      
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-04T20:38:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1007"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 867996b1-5f47-4454-9472-281ded0b599f
